(ns soul-talk.modules.kpn.schema)

(def schame
  {:process/ref.product-task #:db{:valueType :db.type/ref},
   :product-task/ref.sell-detail #:db{:valueType :db.type/ref},
   :organization/id #:db{:unique :db.unique/identity},
   :sell-detail/ref.sell-order #:db{:valueType :db.type/ref},
   :process/flow_detail_id #:db{:unique :db.unique/identity},
   :cost/ref.sell-order #:db{:valueType :db.type/ref},
   :provider/id #:db{:unique :db.unique/identity},
   :machine/machine_id #:db{:unique :db.unique/identity},
   :process/id #:db{:unique :db.unique/identity},
   :material/goods_id #:db{:unique :db.unique/identity},
   :cost/material-log.id #:db{:unique :db.unique/identity},
   :product-task/ref.costs #:db{:valueType :db.type/ref},
   :human/id #:db{:unique :db.unique/identity},
   :cost/id #:db{:unique :db.unique/identity},
   :cost/ref.human #:db{:valueType :db.type/ref},
   :sell-detail/id #:db{:unique :db.unique/identity},
   :sell-detail/detail_id #:db{:unique :db.unique/identity},
   :sell-order/ref.customer #:db{:valueType :db.type/ref},
   :product-task/ref.material-info #:db{:valueType :db.type/ref},
   :human/user_id #:db{:unique :db.unique/identity},
   :product-task/flow_id #:db{:unique :db.unique/identity},
   :material/id #:db{:unique :db.unique/identity},
   :unit/name #:db{:unique :db.unique/identity},
   :machine/id #:db{:unique :db.unique/identity},
   :sell-detail/ref.workshop #:db{:valueType :db.type/ref},
   :sell-order/order_number #:db{:unique :db.unique/identity},
   :cost/ref.process #:db{:valueType :db.type/ref},
   :cost/machine-log.id #:db{:unique :db.unique/identity},
   :place/ref.sub-places
   #:db{:cardinality :db.cardinality/many, :valueType :db.type/ref},
   :cost/ref.machine #:db{:valueType :db.type/ref},
   :product-task/id #:db{:unique :db.unique/identity},
   :cost/ref.product-task #:db{:valueType :db.type/ref},
   :kpn-org/id #:db{:unique :db.unique/identity},
   :customer/id #:db{:unique :db.unique/identity},
   :product-task/ref.workshop #:db{:valueType :db.type/ref},
   :product-task/ref.material #:db{:valueType :db.type/ref},
   :sell-order/ref.order_company #:db{:valueType :db.type/ref},
   :cost/workload-log.id #:db{:unique :db.unique/identity},
   :product-task/ref.energy-info #:db{:valueType :db.type/ref},
   :cost/ref.group #:db{:valueType :db.type/ref},
   :product-task/ref.machine-info #:db{:valueType :db.type/ref},
   :sell-detail/ref.material #:db{:valueType :db.type/ref},
   :product-task/ref.product-company #:db{:valueType :db.type/ref},
   :cost/ref.material #:db{:valueType :db.type/ref},
   :product-task/ref.human-info #:db{:valueType :db.type/ref},
   :cost/craft-log.id #:db{:unique :db.unique/identity},
   :place/code #:db{:unique :db.unique/identity},
   :material/code #:db{:unique :db.unique/identity}})




